# Used when specific branch for given repo does not exist.
default: develop

branches:
  # Specification of branches from which artifacts will be pulled.
  oz-worker: current_branch
  op-worker: current_branch
  onepanel: current_branch
  cluster-manager: current_branch
  oneclient: current_branch
